services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: "run --server --addr 0.0.0.0:8181 --log-level debug /policies/policy.rego /policies/data/global_policy.json /policies/data/tenants.json"
    volumes:
      - ./configs:/policies
